---
title: "Ankara Election"
output: html_document
---


A google image search of [Ankara's mayoral elections outcome](https://www.google.com/search?q=Ankara+mayoral+elections&es_sm=91&source=lnms&tbm=isch&sa=X&ei=DxdgU77yH4zJsQTRiYC4Bg&ved=0CAoQ_AUoAw&biw=1127&bih=598#q=Ankara+mayoral+elections+outcome&tbm=isch&imgdii=_), shows the top results to be of a various scatterplots claiming voter irregularities . 

This is an analysis of the 2014 mayoral elections. After the dataset of the election outcome was released several people tweeted about voter irregularities. The discussion picked up after a post by [erenyanik](https://twitter.com/emeyersson/status/450978793746743298).

[erenyanik](https://twitter.com/emeyersson/status/450978793746743298) shows a plot of the AKP-CHP voter share versus turnout rate. The graph shows that AKP claims the majority of the irregular votes while loosing the regular vote. 


In our project we explore the data, reproduce some of the results already published and add new insights gained from the data. 


1. Explore the data. Create bar plots and scatter plots. 
2. Recreate this [graph](https://twitter.com/emeyersson/status/450978793746743298)
3. Geodesics: Create a map of how the AKP and CHP votes are distributed
4. Conclusion. 



```{r loading the data}
library(readr)
ankara <- read_csv("ankara.csv.zip")
#head(ankara)
#summary(ankara)
names(ankara)
```

#### Let's start by first translating the columns we are interested:    

Turkish ——-> English    
gecerli_oy: valid votes     
gecersiz_oy: disputed votes     
akp_oy: main party     
chp_oy: main opposition party    
mhp_oy: nationalist party    
kayitli_secmen: registered voters     
kullanilan_toplam_oy: actual votes

#### Chapter 1: Creating a bar graph

Select essential columns and transform the data frame

```{}
library(dplyr)
df <- select(ankara, 9, 12, 15, 21, 29, 31)
library(reshape2)
df_l <- melt(df, id=c("itirazsiz_gecerli_oy", "gecersiz_oy"))
head(df_l)
```

Add the value of each group

```{}
df_n <- group_by(df_l, variable) %>% 
        summarize(s = sum(value))
```

Make the bar plot

```{}
library(ggplot2)
pl1 <- ggplot(df_n, aes(x=variable, y=s)) + geom_bar(stat="sum")
print(pl1)
```


```{}
plot(mtcars)
```
